### PR TITLE
Add sdcard backup function

### PR DESCRIPTION
**Pull request by viktorxda**

### CODE REVIEW

**Review by ZigFisher — CHANGES_REQUESTED** [review]
The sdbackup function needs to be discussed

**Comment by viktorxda** [comment]
This is only somewhat useful for testing and debugging (flashing the bootloader with mstar-snander to a new device and make a backup of the remaining firmware).

**Comment by ZigFisher** [comment]
No, you closed it for nothing, you're too fast ;)
I wanted to discuss other details.
I will reopen it and write new ideas.

**Comment by ZigFisher** [comment]
A discussion is expected in the development group this evening.

**Pull request closed without merging**
